######################################################################
# Automatically generated by qmake (2.01a) jeu. 14. juin 11:32:46 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += ../../ImageIn ../../GenericInterface
LIBS += ../../GenericInterface/debug/libGenericInterface.a ../../ImageIn/libimagein.a
LIBS += -lqwt -ljpeg -lpng
QT += testlib

# Input
HEADERS += Tests.moc
SOURCES += Tests.cpp
